import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { commerce } from "../src/lib/commerce";
import ProductsList from '../components/ProductListing'

export async function getStaticProps() {
  const merchant = await commerce.merchants.about();
  const { data: products } = await commerce.products.list();

  return {
    props: {
      merchant,
      products,
    },
  };
}

export default function Home({ merchant, products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ProductsList products={products} />
      </div>
    </div>
  );
}
