import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { commerce } from "../src/lib/commerce";

export async function getStaticProps() {
  const merchant = await commerce.merchants.about();
  const { data: products } = await commerce.products.list();

  return {
    props: {
      merchant,
      products,
    },
  };
}

export default function Home({ merchant, products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>This is the Home Page</h1>
        <div>
          <h1>Merchant</h1>
          <pre>{JSON.stringify(merchant, null, 2)}</pre>
          <h1>Products</h1>
          <pre>{JSON.stringify(products, null, 2)}</pre>
        </div>
      </div>
    </div>
  );
}
